projects:
  defaults:
    os_type: ANDROID
    project_type: APPIUM_ANDROID_SERVER_SIDE
    application_file: bclary-Testdroid.apk
    test_file: bclary-empty-test.zip
    timeout: 0
    scheduler: SINGLE
    archivingStrategy: DAYS
    archivingItemCount: 365
    taskcluster_provisioner_id: proj-autophone
    additional_parameters:
      bitbar_cloud_url: https://mozilla.testdroid.com
      DOCKER_IMAGE_VERSION: 20190109T064727
      TC_WORKER_CONF: gecko-t-ap
  mozilla-unittest-p2:
    device_group_name: pixel2-unit
    device_model: pixel2
    framework_name: mozilla-usb
    description: Mozilla Unit tests for Pixel2
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/bitbar-x-unit-p2
      TC_WORKER_TYPE: gecko-t-ap-unit-p2
  mozilla-perftest-p2:
    device_group_name: pixel2-perf
    device_model: pixel2
    framework_name: mozilla-usb
    description: Mozilla Performance tests for Pixel2
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/bitbar-x-perf-p2
      TC_WORKER_TYPE: gecko-t-ap-perf-p2
  mozilla-perftest-g5:
    device_group_name: motog5-perf
    device_model: motog5
    framework_name: mozilla-usb
    description: Mozilla Performance tests for MotoG5
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/bitbar-x-perf-g5
      TC_WORKER_TYPE: gecko-t-ap-perf-g5
  mozilla-batttest-p2:
    device_group_name: pixel2-batt
    device_model: pixel2
    framework_name: mozilla-tcp
    description: Mozilla Battery tests for Pixel2
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/bitbar-x-batt-p2
      TC_WORKER_TYPE: gecko-t-ap-batt-p2
  mozilla-batttest-g5:
    device_group_name: motog5-batt
    device_model: motog5
    framework_name: mozilla-tcp
    description: Mozilla Battery tests for MotoG5
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/bitbar-x-batt-g5
      TC_WORKER_TYPE: gecko-t-ap-batt-g5
  mozilla-unittest-g5:
    device_group_name: motog5-unit
    device_model: motog5
    framework_name: mozilla-usb
    description: Mozilla Unit tests for MotoG5
    additional_parameters:
      TASKCLUSTER_CLIENT_ID: project/autophone/bitbar-x-unit-g5
      TC_WORKER_TYPE: gecko-t-ap-unit-g5
  mozilla-docker-build:
    device_group_name: motog4-docker-builder
    device_model: motog4
    framework_name: Docker image build
    description: Mozilla Docker image build
    test_file: mozilla-docker-20190206T094537.zip
    application_file: bclary-Testdroid.apk
    additional_parameters:
      DOCKER_IMAGE_VERSION: 20190206T094537
device_groups:
  motog4-docker-builder:
    Docker Builder:
  motog5-batt:
    motog5-08:
    motog5-15:
  motog5-perf:
    motog5-01:
    motog5-02:
    motog5-03:
    motog5-04:
    motog5-05:
    motog5-06:
    motog5-07:
    motog5-09:
    motog5-10:
    motog5-11:
    motog5-12:
    motog5-13:
    motog5-14:
  motog5-unit:
  pixel2-batt:
    pixel2-34:
    pixel2-35:
  pixel2-perf:
    pixel2-26:
    pixel2-27:
    pixel2-28:
    pixel2-29:
    pixel2-30:
    pixel2-24:
    pixel2-25:
    pixel2-31:
    pixel2-32:
    pixel2-33:
  pixel2-unit:
    pixel2-01:
    pixel2-02:
    pixel2-03:
    pixel2-04:
    pixel2-05:
    pixel2-06:
    pixel2-07:
    pixel2-08:
    pixel2-09:
    pixel2-10:
    pixel2-11:
    pixel2-12:
    pixel2-13:
    pixel2-14:
    pixel2-15:
    pixel2-16:
    pixel2-17:
    pixel2-18:
    pixel2-19:
    pixel2-20:
    pixel2-21:
    pixel2-22:
    pixel2-23:
